### ISSUE TITLE
Unable to send messages from QPID JMS client to RabbitMQ with AMQP 1.0 plugin

### ISSUE THREAD

**Issue by fayvaz** [rabbitmq/rabbitmq-amqp1.0#61] opened 2018-04-06 13:37 UTC
Hello -

I am trying to connect and send message from QPID JMS client to RabbitMQ with AMQP 1.0 plugin. However, I could create a durable queue but not achieve to send message and observe the following logs: 

At QPID JMS client side (running HelloWorld example in the QPID JMS example repo):
```
2018-04-06 16:31:19,377 [68.247.44:5672]] - TRACE NettyTcpTransport              - Netty Transport using NIO mode
2018-04-06 16:31:19,799 [ntLoopGroup-2-1] - TRACE NettyTcpTransport              - Channel has become active! Channel is [id: 0x3a680018, L:/217.78.109.51:29431 - R:/47.168.247.44:5672]
2018-04-06 16:31:19,826 [68.247.44:5672]] - TRACE NettyTcpTransport              - Attempted write of: 8 bytes
2018-04-06 16:31:19,841 [ntLoopGroup-2-1] - TRACE NettyTcpTransport              - New data read: 51 bytes incoming: PooledUnsafeDirectByteBuf(ridx: 0, widx: 51, cap: 65536)
2018-04-06 16:31:19,841 [68.247.44:5672]] - DEBUG SaslMechanismFinder            - Skipping SASL-PLAIN mechanism because the available credentials are not sufficient
2018-04-06 16:31:19,841 [68.247.44:5672]] - DEBUG SaslMechanismFinder            - Unknown SASL mechanism: [AMQPLAIN]
2018-04-06 16:31:19,841 [68.247.44:5672]] - INFO  SaslMechanismFinder            - Best match for SASL auth was: SASL-ANONYMOUS
2018-04-06 16:31:19,841 [68.247.44:5672]] - TRACE AmqpProvider                   - New Proton Event: CONNECTION_INIT
2018-04-06 16:31:19,841 [68.247.44:5672]] - TRACE NettyTcpTransport              - Attempted write of: 42 bytes
2018-04-06 16:31:19,841 [ntLoopGroup-2-1] - TRACE NettyTcpTransport              - New data read: 17 bytes incoming: PooledUnsafeDirectByteBuf(ridx: 0, widx: 17, cap: 65536)
2018-04-06 16:31:19,841 [68.247.44:5672]] - TRACE NettyTcpTransport              - Attempted write of: 8 bytes
2018-04-06 16:31:19,857 [ntLoopGroup-2-1] - TRACE NettyTcpTransport              - New data read: 8 bytes incoming: PooledUnsafeDirectByteBuf(ridx: 0, widx: 8, cap: 65536)
2018-04-06 16:31:19,857 [68.247.44:5672]] - TRACE MetaDataSupport                - Problem generating primary version details
java.lang.NullPointerException
	at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
	at java.util.regex.Matcher.reset(Matcher.java:309)
	at java.util.regex.Matcher.<init>(Matcher.java:229)
	at java.util.regex.Pattern.matcher(Pattern.java:1093)
	at org.apache.qpid.jms.util.MetaDataSupport.<clinit>(MetaDataSupport.java:47)
	at org.apache.qpid.jms.provider.amqp.builders.AmqpConnectionBuilder.createEndpoint(AmqpConnectionBuilder.java:116)
	at org.apache.qpid.jms.provider.amqp.builders.AmqpConnectionBuilder.createEndpoint(AmqpConnectionBuilder.java:1)
	at org.apache.qpid.jms.provider.amqp.builders.AmqpResourceBuilder.buildResource(AmqpResourceBuilder.java:76)
	at org.apache.qpid.jms.provider.amqp.builders.AmqpConnectionBuilder.buildResource(AmqpConnectionBuilder.java:58)
	at org.apache.qpid.jms.provider.amqp.AmqpProvider$4$1.processConnectionInfo(AmqpProvider.java:412)
	at org.apache.qpid.jms.meta.JmsConnectionInfo.visit(JmsConnectionInfo.java:417)
	at org.apache.qpid.jms.provider.amqp.AmqpProvider$4.run(AmqpProvider.java:371)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

…

2018-04-06 16:31:19,873 [68.247.44:5672]] - TRACE FRAMES                         - SENT: Open{ containerId='ID:6d6fab0c-f5e6-4618-a407-c54a04b0b439:1', hostname='47.168.247.44', maxFrameSize=1048576, channelMax=32767, idleTimeOut=30000, outgoingLocales=null, incomingLocales=null, offeredCapabilities=null, desiredCapabilities=[sole-connection-for-container, DELAYED_DELIVERY, ANONYMOUS-RELAY, SHARED-SUBS], properties={product=QpidJMS, version=0.32.0-SNAPSHOT, platform=JVM: 1.8.0_161, 25.161-b12, Oracle Corporation, OS: Windows 10, 10.0, amd64}}
2018-04-06 16:31:19,873 [68.247.44:5672]] - TRACE NettyTcpTransport              - Attempted write of: 307 bytes
2018-04-06 16:31:19,873 [68.247.44:5672]] - TRACE AmqpProvider                   - New Proton Event: CONNECTION_LOCAL_OPEN
2018-04-06 16:31:19,873 [ntLoopGroup-2-1] - TRACE NettyTcpTransport              - New data read: 340 bytes incoming: PooledUnsafeDirectByteBuf(ridx: 0, widx: 340, cap: 65536)
2018-04-06 16:31:19,873 [68.247.44:5672]] - TRACE FRAMES                         - RECV: Open{ containerId='rabbit@appstacleserver-HP-Compaq-Elite-8300-MT', hostname='null', maxFrameSize=1048576, channelMax=32767, idleTimeOut=60000, outgoingLocales=null, incomingLocales=null, offeredCapabilities=null, desiredCapabilities=null, properties={cluster_name=rabbit@appstacleserver-HP-Compaq-Elite-8300-MT, copyright=Copyright (C) 2007-2018 Pivotal Software, Inc., information=Licensed under the MPL.  See http://www.rabbitmq.com/, platform=Erlang/OTP 20.2, product=RabbitMQ, version=3.7.4}}
2018-04-06 16:31:19,873 [68.247.44:5672]] - TRACE AmqpProvider                   - New Proton Event: CONNECTION_REMOTE_OPEN
2018-04-06 16:31:19,873 [68.247.44:5672]] - TRACE AmqpProvider                   - New Proton Event: SESSION_INIT
2018-04-06 16:31:19,873 [68.247.44:5672]] - TRACE AmqpProvider                   - New Proton Event: SESSION_LOCAL_OPEN
2018-04-06 16:31:19,873 [68.247.44:5672]] - TRACE FRAMES                         - SENT: Begin{remoteChannel=null, nextOutgoingId=1, incomingWindow=2047, outgoingWindow=2147483647, handleMax=65535, offeredCapabilities=null, desiredCapabilities=null, properties=null}
2018-04-06 16:31:19,873 [68.247.44:5672]] - TRACE NettyTcpTransport              - Attempted write of: 32 bytes
2018-04-06 16:31:19,888 [ntLoopGroup-2-1] - TRACE NettyTcpTransport              - New data read: 36 bytes incoming: PooledUnsafeDirectByteBuf(ridx: 0, widx: 36, cap: 65536)
2018-04-06 16:31:19,888 [68.247.44:5672]] - TRACE FRAMES                         - RECV: Begin{remoteChannel=0, nextOutgoingId=0, incomingWindow=65535, outgoingWindow=65535, handleMax=65535, offeredCapabilities=null, desiredCapabilities=null, properties=null}
2018-04-06 16:31:19,904 [68.247.44:5672]] - TRACE AmqpProvider                   - New Proton Event: SESSION_REMOTE_OPEN
2018-04-06 16:31:19,904 [68.247.44:5672]] - DEBUG AmqpConnectionBuilder          - AmqpConnection { ID:3c1ad029-0598-40a2-964a-b0f83288ded5:1 } is now open: 
2018-04-06 16:31:19,904 [68.247.44:5672]] - TRACE AmqpProvider                   - IdleTimeoutCheck being initiated, initial delay: 30000
2018-04-06 16:31:19,904 [68.247.44:5672]] - INFO  JmsConnection                  - Connection ID:3c1ad029-0598-40a2-964a-b0f83288ded5:1 connected to remote Broker: amqp://47.168.247.44:5672?amqp.traceFrames=true&org.apache.qpid.jms.provider.amqp.FRAMES=TRACE
2018-04-06 16:31:19,904 [68.247.44:5672]] - TRACE FRAMES                         - SENT: Begin{remoteChannel=null, nextOutgoingId=1, incomingWindow=2047, outgoingWindow=2147483647, handleMax=65535, offeredCapabilities=null, desiredCapabilities=null, properties=null}
2018-04-06 16:31:19,904 [68.247.44:5672]] - TRACE NettyTcpTransport              - Attempted write of: 32 bytes
2018-04-06 16:31:19,920 [ntLoopGroup-2-1] - TRACE NettyTcpTransport              - New data read: 36 bytes incoming: PooledUnsafeDirectByteBuf(ridx: 0, widx: 36, cap: 65536)
2018-04-06 16:31:19,920 [68.247.44:5672]] - TRACE FRAMES                         - RECV: Begin{remoteChannel=1, nextOutgoingId=0, incomingWindow=65535, outgoingWindow=65535, handleMax=65535, offeredCapabilities=null, desiredCapabilities=null, properties=null}
2018-04-06 16:31:19,920 [68.247.44:5672]] - TRACE AmqpProvider                   - New Proton Event: SESSION_INIT
2018-04-06 16:31:19,920 [68.247.44:5672]] - TRACE AmqpProvider                   - New Proton Event: SESSION_LOCAL_OPEN
2018-04-06 16:31:19,920 [68.247.44:5672]] - TRACE AmqpProvider                   - New Proton Event: SESSION_REMOTE_OPEN
2018-04-06 16:31:19,920 [68.247.44:5672]] - DEBUG AmqpProducerBuilder            - Creating AmqpFixedProducer for: helloagain
2018-04-06 16:31:19,935 [68.247.44:5672]] - TRACE FRAMES                         - SENT: Attach{name='qpid-jms:sender:ID:3c1ad029-0598-40a2-964a-b0f83288ded5:1:1:1:helloagain', handle=0, role=SENDER, sndSettleMode=UNSETTLED, rcvSettleMode=FIRST, source=Source{address='ID:3c1ad029-0598-40a2-964a-b0f83288ded5:1:1:1', durable=CONFIGURATION, expiryPolicy=SESSION_END, timeout=0, dynamic=false, dynamicNodeProperties=null, distributionMode=null, filter=null, defaultOutcome=null, outcomes=[amqp:accepted:list, amqp:rejected:list, amqp:released:list], capabilities=null}, target=Target{address='helloagain', durable=CONFIGURATION, expiryPolicy=SESSION_END, timeout=0, dynamic=false, dynamicNodeProperties=null, capabilities=[queue]}, unsettled=null, incompleteUnsettled=false, initialDeliveryCount=0, maxMessageSize=null, offeredCapabilities=null, desiredCapabilities=[DELAYED_DELIVERY], properties=null}
2018-04-06 16:31:19,935 [68.247.44:5672]] - TRACE NettyTcpTransport              - Attempted write of: 307 bytes
2018-04-06 16:31:19,935 [ntLoopGroup-2-1] - TRACE NettyTcpTransport              - Exception on channel! Channel is [id: 0x3a680018, L:/217.78.109.51:29431 - R:/47.168.247.44:5672]
2018-04-06 16:31:19,935 [ntLoopGroup-2-1] - TRACE NettyTcpTransport              - Firing onTransportError listener
2018-04-06 16:31:19,935 [68.247.44:5672]] - INFO  AmqpProvider                   - Transport failed: An existing connection was forcibly closed by the remote host
2018-04-06 16:31:19,935 [ntLoopGroup-2-1] - TRACE NettyTcpTransport              - Channel has gone inactive! Channel is [id: 0x3a680018, L:/217.78.109.51:29431 ! R:/47.168.247.44:5672]
Connection ExceptionListener fired, exiting.
javax.jms.JMSException: An existing connection was forcibly closed by the remote host
	at org.apache.qpid.jms.exceptions.JmsExceptionSupport.create(JmsExceptionSupport.java:86)
	at org.apache.qpid.jms.exceptions.JmsExceptionSupport.create(JmsExceptionSupport.java:108)
	at org.apache.qpid.jms.JmsConnection.onAsyncException(JmsConnection.java:1392)
	at org.apache.qpid.jms.JmsConnection.onProviderException(JmsConnection.java:1376)
	at org.apache.qpid.jms.JmsConnection.onConnectionFailure(JmsConnection.java:1244)
	at org.apache.qpid.jms.provider.amqp.AmqpProvider.fireProviderException(AmqpProvider.java:1086)
	at org.apache.qpid.jms.provider.amqp.AmqpProvider$18.run(AmqpProvider.java:859)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:345)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
Caught exception, exiting.
javax.jms.JMSException: An existing connection was forcibly closed by the remote host
	at org.apache.qpid.jms.exceptions.JmsExceptionSupport.create(JmsExceptionSupport.java:86)
	at org.apache.qpid.jms.exceptions.JmsExceptionSupport.create(JmsExceptionSupport.java:108)
	at org.apache.qpid.jms.JmsConnection.createResource(JmsConnection.java:615)
	at org.apache.qpid.jms.JmsConnection.createResource(JmsConnection.java:599)
	at org.apache.qpid.jms.JmsMessageProducer.<init>(JmsMessageProducer.java:73)
	at org.apache.qpid.jms.JmsSession.createProducer(JmsSession.java:603)
	at org.apache.qpid.jms.example.HelloWorld.main(HelloWorld.java:54)
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method)

```

At RabbitMQ side:

```
2018-04-06 16:31:21.880 [info] <0.17194.6> accepting AMQP connection <0.17194.6> (217.78.109.51:29431 -> 47.168.247.44:5672)
2018-04-06 16:31:21.986 [error] <0.17216.6> CRASH REPORT Process <0.17216.6> with 0 neighbours crashed with reason: no function clause matching rabbit_amqp1_0_binary_generator:generate({array,[{symbol,<<"amqp:accepted:list">>},{symbol,<<"amqp:rejected:list">>},{symbol,<<"amqp:releas...">>}]}) line 42
2018-04-06 16:31:21.987 [error] <0.17215.6> Supervisor {<0.17215.6>,rabbit_amqp1_0_session_sup} had child writer started with rabbit_amqp1_0_writer:start_link(#Port<0.1441079>, 1, 1048568, rabbit_amqp1_0_framing, <0.17194.6>) at <0.17216.6> exit with reason no function clause matching rabbit_amqp1_0_binary_generator:generate({array,[{symbol,<<"amqp:accepted:list">>},{symbol,<<"amqp:rejected:list">>},{symbol,<<"amqp:releas...">>}]}) line 42 in context child_terminated
2018-04-06 16:31:21.987 [error] <0.17215.6> Supervisor {<0.17215.6>,rabbit_amqp1_0_session_sup} had child writer started with rabbit_amqp1_0_writer:start_link(#Port<0.1441079>, 1, 1048568, rabbit_amqp1_0_framing, <0.17194.6>) at <0.17216.6> exit with reason reached_max_restart_intensity in context shutdown
2018-04-06 16:31:21.987 [error] <0.17194.6> CRASH REPORT Process <0.17194.6> with 0 neighbours crashed with reason: no match of right hand value shutdown in rabbit_amqp1_0_reader:handle_dependent_exit/3 line 253
2018-04-06 16:31:21.987 [error] <0.17192.6> Supervisor {<0.17192.6>,rabbit_connection_sup} had child reader started with rabbit_reader:start_link(<0.17193.6>, {acceptor,{0,0,0,0,0,0,0,0},5672}, #Port<0.1441079>) at <0.17194.6> exit with reason no match of right hand value shutdown in rabbit_amqp1_0_reader:handle_dependent_exit/3 line 253 in context child_terminated
2018-04-06 16:31:21.988 [error] <0.17192.6> Supervisor {<0.17192.6>,rabbit_connection_sup} had child reader started with rabbit_reader:start_link(<0.17193.6>, {acceptor,{0,0,0,0,0,0,0,0},5672}, #Port<0.1441079>) at <0.17194.6> exit with reason reached_max_restart_intensity in context shutdown
```

**Comment by kjnilsson** [comment] 2018-04-06 13:53
Hi, thanks for the report. Looks like there is a bug in the binary serialisation of amqp arrays.

**Comment by fayvaz** [comment] 2018-04-06 13:59
Many thanks Karl for your quick reply. Is there any workaround solution to move forward?

**Comment by kjnilsson** [comment] 2018-04-06 14:28
I can't think of a workaround unless you can get the client not to emit the array.

**Comment by michaelklishin** [comment] 2018-04-06 16:05
@fayvaz can you please put together a small example that can be used to reproduce? That would help us a lot. Thanks.

**Comment by fayvaz** [comment] 2018-04-09 05:07
@michaelklishin My scenario ans setup are given below step by step:
-QPID JMS client installed on Windows environment.
-RabbitMQ installed on Ubuntu 16.04 with AMQP 1.0 plugin.
-durable in Terminus class under QPID PROTON-J library changed to CONFIGURATION and it is built (the aim is to set the durable at Source and Target to CONFIGURATION)
-removed Modified outcome value in AmqpProducerBuild under org.apache.qpid.jms.provider.amqp.builders (since AMQP 1.0 plugin does not support Modified value). 

I have run the HelloWorld example in QPID JMS example to make a AMQP 1.0 connection between the client and RabbitMQ and the problem happens.

I hope this explanation is quite clear.

thanks,
-fatih

**Comment by kjnilsson** [comment] 2018-04-09 08:13
I suspect just trying to roundtrip an array from and to binary will trigger the error. It should be fixed in https://github.com/rabbitmq/rabbitmq-amqp1.0-common and this repo should be updated to take common as a dependency and use the serializers in there.

**Comment by fayvaz** [comment] 2018-04-09 08:42
@kjnilsson I will be appreacited if you could provide more info how to try this proposal.

**Comment by kjnilsson** [comment] 2018-04-09 08:47
@fayvaz I think this is more of something we need to address. We extracted the serializers out into a common library when we write the amqp 1.0 client but we missed to update this repo to also use the common lib.

**Comment by fayvaz** [comment] 2018-04-09 09:15
@kjnilsson Do you have a plan to fix this? How can I use that in my scenario?

**Comment by michaelklishin** [comment] 2018-04-09 09:16
@fayvaz we do have a plan to fix this, please be patient.

**Comment by fayvaz** [comment] 2018-04-09 09:56
@michaelklishin @kjnilsson many thanks for your support.

**Comment by kjnilsson** [comment] 2018-04-10 13:15
@fayvaz did you have to modify proton itself to remove the request for the modified outcome or can it be done some other way?  if so could you provide an example? Cheers.

**Comment by fayvaz** [comment] 2018-04-11 05:04
I did change in the qpid.jms.provider.amqp.builders.AmqpProducerBuilder class and comment out the modified outcome in Serder method.

**Comment by easystreet** [comment] 2018-04-11 19:47
Hello,  I'm also experiencing this issue (I think) but via Informatica AMQP connector.  The connection is attempting to send a test static test message to queue 'writetest' but Informatica errors with:  

`"Error executing cloud process [hostRuntimeCall] with id [12505]: Session is closed while creating link, target: writetest"`

And here is the log entry:  

`2018-04-11 15:23:04.749 [info] <0.5.0> Server startup complete; 4 plugins started.
 * rabbitmq_management
 * rabbitmq_management_agent
 * rabbitmq_web_dispatch
 * rabbitmq_amqp1_0
2018-04-11 15:30:06.007 [info] <0.638.0> accepting AMQP connection <0.638.0> (127.0.0.1:60509 -> 127.0.0.1:5672)
2018-04-11 15:30:07.444 [info] <0.638.0> closing AMQP connection <0.638.0> (127.0.0.1:60509 -> 127.0.0.1:5672)
2018-04-11 15:30:09.757 [info] <0.592.0> closing AMQP connection <0.592.0> (127.0.0.1:60350 -> 127.0.0.1:5672)
2018-04-11 15:30:09.804 [info] <0.680.0> accepting AMQP connection <0.680.0> (127.0.0.1:60512 -> 127.0.0.1:5672)
2018-04-11 15:31:49.767 [info] <0.711.0> accepting AMQP connection <0.711.0> (127.0.0.1:60549 -> 127.0.0.1:5672)
2018-04-11 15:31:49.876 [error] <0.716.0> CRASH REPORT Process <0.716.0> with 0 neighbours crashed with reason: no function clause matching rabbit_amqp1_0_binary_generator:generate({array,[{symbol,<<"amqp:accepted:list">>},{symbol,<<"amqp:rejected:list">>}]}) line 42
2018-04-11 15:31:49.876 [error] <0.715.0> Supervisor {<0.715.0>,rabbit_amqp1_0_session_sup} had child writer started with rabbit_amqp1_0_writer:start_link(#Port<0.30933>, 0, 65528, rabbit_amqp1_0_framing, <0.711.0>) at <0.716.0> exit with reason no function clause matching rabbit_amqp1_0_binary_generator:generate({array,[{symbol,<<"amqp:accepted:list">>},{symbol,<<"amqp:rejected:list">>}]}) line 42 in context child_terminated
2018-04-11 15:31:49.876 [error] <0.715.0> Supervisor {<0.715.0>,rabbit_amqp1_0_session_sup} had child writer started with rabbit_amqp1_0_writer:start_link(#Port<0.30933>, 0, 65528, rabbit_amqp1_0_framing, <0.711.0>) at <0.716.0> exit with reason reached_max_restart_intensity in context shutdown
2018-04-11 15:31:49.876 [error] <0.711.0> CRASH REPORT Process <0.711.0> with 0 neighbours crashed with reason: no match of right hand value shutdown in rabbit_amqp1_0_reader:handle_dependent_exit/3 line 253
2018-04-11 15:31:49.876 [error] <0.709.0> Supervisor {<0.709.0>,rabbit_connection_sup} had child reader started with rabbit_reader:start_link(<0.710.0>, {acceptor,{0,0,0,0},5672}, #Port<0.30933>) at <0.711.0> exit with reason no match of right hand value shutdown in rabbit_amqp1_0_reader:handle_dependent_exit/3 line 253 in context child_terminated
2018-04-11 15:31:49.876 [error] <0.709.0> Supervisor {<0.709.0>,rabbit_connection_sup} had child reader started with rabbit_reader:start_link(<0.710.0>, {acceptor,{0,0,0,0},5672}, #Port<0.30933>) at <0.711.0> exit with reason reached_max_restart_intensity in context shutdown
`
This seems to occur with both 3.6.10 and 3.7.3 (I have two separate instances,  both are failing).
Is there any more information I can provide?  

This also seems similar to closed issue #31.

**Comment by kjnilsson** [comment] 2018-04-12 08:18
@easystreet I take it the Informatica AMQP connector uses the QPid JMS client? Anyhow we're currently working on this issue together with #57 to provide better JMS compatibilty.

**Comment by fayvaz** [comment] 2018-04-12 08:28
@kjnilsson We did comment out the outcome values in AmqpMessageProducer and AmqpMessageConsumer classes and it works as a workaround. We could send messages from QPID JMS client to RabbitMQ right now. When the plugin fix is ready, we will enable the codes again.

**Closed** 2018-04-23 15:59 UTC
Labels: bug
