### ISSUE TITLE
Handshake error for AMQP 1.0

### ISSUE THREAD

**Issue by tudvari** [rabbitmq/rabbitmq-amqp1.0#55] opened 2017-07-28 14:01 UTC
Hi,

I would like to use this plugin with rabbitmq 3.5, but I have the followed error message:

```
=INFO REPORT==== 28-Jul-2017::13:59:31 ===
accepting AMQP connection <0.5190.0> (172.17.0.1:59058 -> 172.17.0.2:5672)

=ERROR REPORT==== 28-Jul-2017::13:59:31 ===
** Generic server <0.5212.0> terminating
** Last message in was {'$gen_cast',
                        {frame,
                         {'v1_0.attach',
                          {utf8,
                           <<"qpid-jms:sender:ID:c69b06a5-ef8c-4795-a522-0503de00c95f:1:1:1:queue">>},
                          {uint,0},
                          false,
                          {ubyte,0},
                          {ubyte,0},
                          {'v1_0.source',
                           {utf8,
                            <<"ID:c69b06a5-ef8c-4795-a522-0503de00c95f:1:1:1">>},
                           {uint,0},
                           {symbol,<<"session-end">>},
                           {uint,0},
                           false,undefined,undefined,undefined,undefined,
                           {list,
                            [{symbol,<<"amqp:accepted:list">>},
                             {symbol,<<"amqp:rejected:list">>},
                             {symbol,<<"amqp:released:list">>},
                             {symbol,<<"amqp:modified:list">>}]},
                           undefined},
                          {'v1_0.target',
                           {utf8,<<"queue">>},
                           {uint,0},
                           {symbol,<<"session-end">>},
                           {uint,0},
                           false,undefined,
                           {list,[{symbol,<<"queue">>}]}},
                          undefined,false,
                          {uint,0},
                          undefined,undefined,
                          {list,[{symbol,<<"DELAYED_DELIVERY">>}]},
                          undefined},
                         <0.5190.0>}}
** When Server state == {state,<0.5215.0>,<0.5221.0>,1048568,<0.5190.0>,
                            <0.5211.0>,
                            {[],[]},
                            {session,1,2047,2147483647,1,65535,65535,0,65535,
                                65535,0,0,
                                {0,nil},
                                {0,nil}}}
** Reason for termination == 
** {function_clause,
       [{rabbit_amqp1_0_link_util,'-outcomes/1-lc$^0/1-0-',
            [{list,
                 [{symbol,<<"amqp:accepted:list">>},
                  {symbol,<<"amqp:rejected:list">>},
                  {symbol,<<"amqp:released:list">>},
                  {symbol,<<"amqp:modified:list">>}]}],
            []},
        {rabbit_amqp1_0_link_util,outcomes,1,[]},
        {rabbit_amqp1_0_incoming_link,attach,3,[]},
        {rabbit_amqp1_0_session_process,with_disposable_channel,2,[]},
        {rabbit_amqp1_0_session_process,handle_control,2,[]},
        {rabbit_amqp1_0_session_process,handle_cast,2,[]},
        {gen_server2,handle_msg,2,[]},
        {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}

=CRASH REPORT==== 28-Jul-2017::13:59:31 ===
  crasher:
    initial call: gen:init_it/6
    pid: <0.5212.0>
    registered_name: []
    exception exit: {function_clause,
                        [{rabbit_amqp1_0_link_util,'-outcomes/1-lc$^0/1-0-',
                             [{list,
                                  [{symbol,<<"amqp:accepted:list">>},
                                   {symbol,<<"amqp:rejected:list">>},
                                   {symbol,<<"amqp:released:list">>},
                                   {symbol,<<"amqp:modified:list">>}]}],
                             []},
                         {rabbit_amqp1_0_link_util,outcomes,1,[]},
                         {rabbit_amqp1_0_incoming_link,attach,3,[]},
                         {rabbit_amqp1_0_session_process,
                             with_disposable_channel,2,[]},
                         {rabbit_amqp1_0_session_process,handle_control,2,[]},
                         {rabbit_amqp1_0_session_process,handle_cast,2,[]},
                         {gen_server2,handle_msg,2,[]},
                         {proc_lib,init_p_do_apply,3,
                             [{file,"proc_lib.erl"},{line,240}]}]}
      in function  gen_server2:terminate/3 
    ancestors: [<0.5210.0>,<0.5191.0>,<0.5189.0>,<0.5188.0>,
                  rabbit_tcp_client_sup,rabbit_sup,<0.73.0>]
    messages: []
    links: [<0.5210.0>]
    dictionary: [{credit_flow_default_credit,{200,50}},
                  {{credit_to,<0.5190.0>},48}]
    trap_exit: true
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 533
  neighbours:

=SUPERVISOR REPORT==== 28-Jul-2017::13:59:31 ===
     Supervisor: {<0.5210.0>,rabbit_amqp1_0_session_sup}
     Context:    child_terminated
     Reason:     {function_clause,
                     [{rabbit_amqp1_0_link_util,'-outcomes/1-lc$^0/1-0-',
                          [{list,
                               [{symbol,<<"amqp:accepted:list">>},
                                {symbol,<<"amqp:rejected:list">>},
                                {symbol,<<"amqp:released:list">>},
                                {symbol,<<"amqp:modified:list">>}]}],
                          []},
                      {rabbit_amqp1_0_link_util,outcomes,1,[]},
                      {rabbit_amqp1_0_incoming_link,attach,3,[]},
                      {rabbit_amqp1_0_session_process,
                          with_disposable_channel,2,[]},
                      {rabbit_amqp1_0_session_process,handle_control,2,[]},
                      {rabbit_amqp1_0_session_process,handle_cast,2,[]},
                      {gen_server2,handle_msg,2,[]},
                      {proc_lib,init_p_do_apply,3,
                          [{file,"proc_lib.erl"},{line,240}]}]}
     Offender:   [{pid,<0.5212.0>},
                  {name,channel},
                  {mfargs,
                      {rabbit_amqp1_0_session_process,start_link,
                          [{1,<0.5190.0>,<0.5211.0>,
                            {user,<<"guest">>,
                                [administrator],
                                [{rabbit_auth_backend_internal,none}]},
                            <<"/">>,1048568,
                            {amqp_adapter_info,
                                {0,0,0,0,0,65535,44049,2},
                                5672,
                                {0,0,0,0,0,65535,44049,1},
                                59058,
                                <<"172.17.0.1:59058 -> 172.17.0.2:5672">>,
                                {'AMQP',"1.0"},
                                [{ssl,false}]},
                            <0.5192.0>}]}},
                  {restart_type,intrinsic},
                  {shutdown,4294967295},
                  {child_type,worker}]


=SUPERVISOR REPORT==== 28-Jul-2017::13:59:31 ===
     Supervisor: {<0.5210.0>,rabbit_amqp1_0_session_sup}
     Context:    shutdown
     Reason:     reached_max_restart_intensity
     Offender:   [{pid,<0.5212.0>},
                  {name,channel},
                  {mfargs,
                      {rabbit_amqp1_0_session_process,start_link,
                          [{1,<0.5190.0>,<0.5211.0>,
                            {user,<<"guest">>,
                                [administrator],
                                [{rabbit_auth_backend_internal,none}]},
                            <<"/">>,1048568,
                            {amqp_adapter_info,
                                {0,0,0,0,0,65535,44049,2},
                                5672,
                                {0,0,0,0,0,65535,44049,1},
                                59058,
                                <<"172.17.0.1:59058 -> 172.17.0.2:5672">>,
                                {'AMQP',"1.0"},
                                [{ssl,false}]},
                            <0.5192.0>}]}},
                  {restart_type,intrinsic},
                  {shutdown,4294967295},
                  {child_type,worker}]
```

My rabbitmq.config looks like this

```
[
	{ rabbit, [
		{ loopback_users, [ ] },
		{ tcp_listeners, [ 5672 ] },
		{ ssl_listeners, [ ] },
		{ hipe_compile, false }
	] },
	{ rabbitmq_management, [ { listener, [
		{ port, 15672 },
		{ ssl, false }
	] } ] },
	{rabbitmq_amqp1_0,[
	  {default_user,"guest"},
          {protocol_strict_mode, false},
          {default_vhost,<<"/">>}
	]}

]
```

Could you help me please? 

Thanks in advance.

**Comment by michaelklishin** [comment] 2017-07-28 14:02
Duplicate of #31.

**Closed by michaelklishin** 2017-07-28 14:02 UTC
